// Wails RPC bindings stub - will be auto-generated by wails dev
// This is a temporary stub to allow frontend build

import * as connection from '../tablepro/connection';
import * as query from '../tablepro/query';
import * as change from '../tablepro/change';

export function ListConnections(): Promise<connection.DatabaseConnection[]> {
  return window.go?.main?.App?.ListConnections?.() || Promise.resolve([]);
}

export function ExecutePaginated(
  connectionID: string,
  queryStr: string,
  page: number,
  pageSize: number
): Promise<query.QueryResult> {
  return window.go?.main?.App?.ExecutePaginated?.(connectionID, queryStr, page, pageSize) || Promise.resolve({} as query.QueryResult);
}

export function GetRowCount(
  connectionID: string,
  queryStr: string
): Promise<query.CountResult> {
  return window.go?.main?.App?.GetRowCount?.(connectionID, queryStr) || Promise.resolve({} as query.CountResult);
}

export function UpdateCell(
  tabID: string,
  rowIndex: number,
  column: string,
  originalValue: any,
  newValue: any,
  primaryKey: Record<string, any>
): Promise<void> {
  return window.go?.main?.App?.UpdateCell?.(tabID, rowIndex, column, originalValue, newValue, primaryKey) || Promise.resolve();
}

export function InsertRow(
  tabID: string,
  data: Record<string, any>
): Promise<string> {
  return window.go?.main?.App?.InsertRow?.(tabID, data) || Promise.resolve('');
}

export function DeleteRow(
  tabID: string,
  primaryKey: Record<string, any>,
  rowIndex: number
): Promise<void> {
  return window.go?.main?.App?.DeleteRow?.(tabID, primaryKey, rowIndex) || Promise.resolve();
}

export function GetPendingChanges(tabID: string): Promise<change.PendingChanges> {
  return window.go?.main?.App?.GetPendingChanges?.(tabID) || Promise.resolve({} as change.PendingChanges);
}

export function DiscardChanges(tabID: string): Promise<void> {
  return window.go?.main?.App?.DiscardChanges?.(tabID) || Promise.resolve();
}

export function UndoChange(tabID: string): Promise<void> {
  return window.go?.main?.App?.UndoChange?.(tabID) || Promise.resolve();
}

export function RedoChange(tabID: string): Promise<void> {
  return window.go?.main?.App?.RedoChange?.(tabID) || Promise.resolve();
}
