// Wails runtime mock - this file will be generated by Wails CLI during build
// For development and testing, we use mocks

export function EventsOn(event: string, handler: (...args: any[]) => void): () => void {
  if (typeof window !== 'undefined' && (window as any).Wails?.EventsOn) {
    return (window as any).Wails.EventsOn(event, handler);
  }
  // Return a no-op cleanup function for testing
  return () => {};
}

export function EventsOff(event: string): void {
  if (typeof window !== 'undefined' && (window as any).Wails?.EventsOff) {
    (window as any).Wails.EventsOff(event);
  }
}

export function EventsEmit(event: string, ...data: any[]): void {
  if (typeof window !== 'undefined' && (window as any).Wails?.EventsEmit) {
    (window as any).Wails.EventsEmit(event, ...data);
  }
}
