// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelQuery(arg1, arg2) {
  return window['go']['main']['App']['CancelQuery'](arg1, arg2);
}

export function ClearQueryHistory(arg1, arg2) {
  return window['go']['main']['App']['ClearQueryHistory'](arg1, arg2);
}

export function DeleteConnection(arg1, arg2) {
  return window['go']['main']['App']['DeleteConnection'](arg1, arg2);
}

export function DeletePassword(arg1, arg2) {
  return window['go']['main']['App']['DeletePassword'](arg1, arg2);
}

export function DeleteRow(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteRow'](arg1, arg2, arg3, arg4);
}

export function DiscardChanges(arg1, arg2) {
  return window['go']['main']['App']['DiscardChanges'](arg1, arg2);
}

export function DuplicateConnection(arg1, arg2) {
  return window['go']['main']['App']['DuplicateConnection'](arg1, arg2);
}

export function ExecuteMultiStatement(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteMultiStatement'](arg1, arg2, arg3);
}

export function ExecutePaginated(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ExecutePaginated'](arg1, arg2, arg3, arg4, arg5);
}

export function ExecuteQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2, arg3);
}

export function ExecuteQueryWithTimeout(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteQueryWithTimeout'](arg1, arg2, arg3, arg4);
}

export function GetConnection(arg1, arg2) {
  return window['go']['main']['App']['GetConnection'](arg1, arg2);
}

export function GetPassword(arg1, arg2) {
  return window['go']['main']['App']['GetPassword'](arg1, arg2);
}

export function GetPendingChanges(arg1, arg2) {
  return window['go']['main']['App']['GetPendingChanges'](arg1, arg2);
}

export function GetQueryHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetQueryHistory'](arg1, arg2, arg3);
}

export function GetRowCount(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetRowCount'](arg1, arg2, arg3);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InitChangeTracking(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['InitChangeTracking'](arg1, arg2, arg3, arg4, arg5);
}

export function InsertRow(arg1, arg2, arg3) {
  return window['go']['main']['App']['InsertRow'](arg1, arg2, arg3);
}

export function ListConnections(arg1) {
  return window['go']['main']['App']['ListConnections'](arg1);
}

export function RedoChange(arg1, arg2) {
  return window['go']['main']['App']['RedoChange'](arg1, arg2);
}

export function SaveConnection(arg1, arg2) {
  return window['go']['main']['App']['SaveConnection'](arg1, arg2);
}

export function SavePassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['SavePassword'](arg1, arg2, arg3);
}

export function TestConnection(arg1, arg2) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2);
}

export function UndoChange(arg1, arg2) {
  return window['go']['main']['App']['UndoChange'](arg1, arg2);
}

export function UpdateCell(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateCell'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ValidateConnection(arg1, arg2) {
  return window['go']['main']['App']['ValidateConnection'](arg1, arg2);
}
