// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {connection} from '../models';
import {query} from '../models';
import {change} from '../models';

export function CancelQuery(arg1:context.Context,arg2:string):Promise<void>;

export function ClearQueryHistory(arg1:context.Context,arg2:string):Promise<void>;

export function DeleteConnection(arg1:context.Context,arg2:string):Promise<void>;

export function DeletePassword(arg1:context.Context,arg2:string):Promise<void>;

export function DeleteRow(arg1:context.Context,arg2:string,arg3:Record<string, any>,arg4:number):Promise<void>;

export function DiscardChanges(arg1:context.Context,arg2:string):Promise<void>;

export function DuplicateConnection(arg1:context.Context,arg2:string):Promise<connection.DatabaseConnection>;

export function ExecuteMultiStatement(arg1:context.Context,arg2:string,arg3:string):Promise<query.MultiStatementResult>;

export function ExecutePaginated(arg1:context.Context,arg2:string,arg3:string,arg4:number,arg5:number):Promise<query.QueryResult>;

export function ExecuteQuery(arg1:context.Context,arg2:string,arg3:string):Promise<query.QueryResult>;

export function ExecuteQueryWithTimeout(arg1:context.Context,arg2:string,arg3:string,arg4:number):Promise<query.QueryResult>;

export function GetConnection(arg1:context.Context,arg2:string):Promise<connection.DatabaseConnection>;

export function GetPassword(arg1:context.Context,arg2:string):Promise<string>;

export function GetPendingChanges(arg1:context.Context,arg2:string):Promise<change.PendingChanges>;

export function GetQueryHistory(arg1:context.Context,arg2:string,arg3:number):Promise<Array<query.QueryHistoryEntry>>;

export function GetRowCount(arg1:context.Context,arg2:string,arg3:string):Promise<query.CountResult>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InitChangeTracking(arg1:context.Context,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<void>;

export function InsertRow(arg1:context.Context,arg2:string,arg3:Record<string, any>):Promise<string>;

export function ListConnections(arg1:context.Context):Promise<Array<connection.DatabaseConnection>>;

export function RedoChange(arg1:context.Context,arg2:string):Promise<void>;

export function SaveConnection(arg1:context.Context,arg2:connection.DatabaseConnection):Promise<void>;

export function SavePassword(arg1:context.Context,arg2:string,arg3:string):Promise<void>;

export function TestConnection(arg1:context.Context,arg2:connection.DatabaseConnection):Promise<connection.TestConnectionResult>;

export function UndoChange(arg1:context.Context,arg2:string):Promise<void>;

export function UpdateCell(arg1:context.Context,arg2:string,arg3:number,arg4:string,arg5:any,arg6:any,arg7:Record<string, any>):Promise<void>;

export function ValidateConnection(arg1:context.Context,arg2:connection.DatabaseConnection):Promise<void>;
