// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {connection} from '../models';

export function DeleteConnection(arg1:context.Context,arg2:string):Promise<void>;

export function DeletePassword(arg1:context.Context,arg2:string):Promise<void>;

export function DuplicateConnection(arg1:context.Context,arg2:string):Promise<connection.DatabaseConnection>;

export function GetConnection(arg1:context.Context,arg2:string):Promise<connection.DatabaseConnection>;

export function GetPassword(arg1:context.Context,arg2:string):Promise<string>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListConnections(arg1:context.Context):Promise<Array<connection.DatabaseConnection>>;

export function SaveConnection(arg1:context.Context,arg2:connection.DatabaseConnection):Promise<void>;

export function SavePassword(arg1:context.Context,arg2:string,arg3:string):Promise<void>;

export function TestConnection(arg1:context.Context,arg2:connection.DatabaseConnection):Promise<connection.TestConnectionResult>;

export function ValidateConnection(arg1:context.Context,arg2:connection.DatabaseConnection):Promise<void>;
