// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteConnection(arg1, arg2) {
  return window['go']['main']['App']['DeleteConnection'](arg1, arg2);
}

export function DeletePassword(arg1, arg2) {
  return window['go']['main']['App']['DeletePassword'](arg1, arg2);
}

export function DuplicateConnection(arg1, arg2) {
  return window['go']['main']['App']['DuplicateConnection'](arg1, arg2);
}

export function GetConnection(arg1, arg2) {
  return window['go']['main']['App']['GetConnection'](arg1, arg2);
}

export function GetPassword(arg1, arg2) {
  return window['go']['main']['App']['GetPassword'](arg1, arg2);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListConnections(arg1) {
  return window['go']['main']['App']['ListConnections'](arg1);
}

export function SaveConnection(arg1, arg2) {
  return window['go']['main']['App']['SaveConnection'](arg1, arg2);
}

export function SavePassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['SavePassword'](arg1, arg2, arg3);
}

export function TestConnection(arg1, arg2) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2);
}

export function ValidateConnection(arg1, arg2) {
  return window['go']['main']['App']['ValidateConnection'](arg1, arg2);
}
